name: pagatu-pedidos-prod

services:
  postgres-pedidos:
    image: postgres:16-alpine
    container_name: pagatu-postgres-pedidos
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    volumes:
      - pagatu_pedidos_data:/var/lib/postgresql/data
    ports:
      - "25433:5432"
    networks:
      - pagatu-pedidos-int

  pedidos-ms:
    build: .
    restart: unless-stopped
    depends_on:
      postgres-pedidos:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      DB_HOST: pagatu-postgres-pedidos
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    volumes:
      - ./logs:/app/logs
    networks:
      - pagatu-pedidos-int

volumes:
  pagatu_pedidos_data:

networks:
  pagatu-pedidos-int:
    name: pagatu-pedidos-int
