CREATE TABLE IF NOT EXISTS ordenes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    cliente_nombre VARCHAR(120) NOT NULL,
    descripcion VARCHAR(255),
    total NUMERIC(12,2) NOT NULL,
    estado VARCHAR(30) NOT NULL,
    fecha_creacion TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_ordenes_estado ON ordenes (estado);
